import type { Metadata } from "next";
import "./globals.css";
import "./reset.css"
import localFont from "next/font/local";
import HeaderComponent from '@/app/components/HeaderComponent';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../static/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="kr" className={`${pretendard.variable}`}>
      <body className={pretendard.className} style={{backgroundColor: "white"}}>
        <div id={"container"} style={{height: "100%", margin: "auto"}}>
         <HeaderComponent />
          {children}
          <div style={{backgroundColor: "#343A40", height: "100px"}}>
            푸터
          </div>
        </div>
      </body>
    </html>
  );
}
